# fly.toml app configuration file generated for golang-app on 2023-09-30T16:09:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "golang-app"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
